dashpay/android-dashpay

examples/src/main/kotlin/org/dashevo/examples/SearchNames.kt
platform-core/src/main/kotlin/org/dashevo/platform/Documents.kt
platform-core/src/main/kotlin/org/dashevo/platform/Names.kt

This adds name search functionality (only using startsWith because Platform does not support full text search).
An example was added for testing

Names: Add search for username support

---

dashpay/src/main/kotlin/org/dashevo/dashpay/ContactRequests.kt
examples/src/main/kotlin/org/dashevo/examples/ShowContactRequests.kt

This depends on #2.  (some code is duplicated, but needs to be refactored)
This allows for queries on contact requests for a userId and to a userId.

Add ContactRequest class

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/ContactRequests.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/Profiles.kt
examples/src/main/kotlin/org/dashevo/examples/DashPayProfiles.kt
examples/src/main/kotlin/org/dashevo/examples/PreorderdNames.kt
examples/src/main/kotlin/org/dashevo/examples/RegisteredNames.kt
examples/src/main/kotlin/org/dashevo/examples/SearchNames.kt
examples/src/main/kotlin/org/dashevo/examples/ShowContactRequests.kt
platform-core/src/main/kotlin/org/dashevo/platform/Names.kt

This goes with PR https://github.com/dashevo/dash-wallet/pull/418 on Dash Wallet.
This PR adds functions that aid in the recovery of a identity, username and profile for an existing user, given the identity id (uniqueId).
This PR refactors the **Profiles** class to move `BlockchainIdentity` related items such as the identity object and encryption keys into the `BlockchainIdentity` class.

NMA-390  Add recovery methods

---

platform-core/src/main/kotlin/org/dashevo/platform/Names.kt

Remove getPreordersByUserId which serves no purpose

NMA-339: Names: Fix query for usernames from userId, add getList for names

---

examples/src/main/kotlin/org/dashevo/examples/CreateWallets.kt
examples/src/main/kotlin/org/dashevo/examples/GetStatus.kt
examples/src/main/kotlin/org/dashevo/examples/RegisteredNames.kt

- CreateWallets - Creates wallets for each given username and prints out the associated recovery phrase. This must connect successfully a devnet client with dash-cli.  It will create wallet and then fund that wallet.  Next it will perform the username registration.
This requires https://github.com/dashevo/dashj/pull/78 to work properly, otherwise it will crash
- GetStatus - Makes 20 attempts to call getStatus() and if that fails, then getBlockById()
- RegisteredNames - format output to justify names and identity strings

Add Examples

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
examples/src/main/java/org/dashevo/examples/ForwardingServiceEvo.java
examples/src/main/kotlin/org/dashevo/examples/CreateWallets.kt
platform-core/src/main/kotlin/org/dashevo/Client.kt
platform-core/src/main/kotlin/org/dashevo/platform/Platform.kt

This requires this PR:
https://github.com/dashevo/dapi-client-android/pull/7

BlockchainIdentity: Fix a crash and use the specified Platform object

---

README.md
build.gradle
dashpay/build.gradle
dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/ContactRequests.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/Profiles.kt
dashpay/src/test/kotlin/org/dashevo/platform/NamesTest.kt
examples/build.gradle
examples/src/main/java/org/dashevo/examples/ForwardingServiceEvo.java
examples/src/main/java/org/dashevo/examples/ShowRegisteredNames.java
examples/src/main/kotlin/org/dashevo/examples/CreateIdentity.kt
examples/src/main/kotlin/org/dashevo/examples/CreateWallets.kt
examples/src/main/kotlin/org/dashevo/examples/DashPayProfiles.kt
examples/src/main/kotlin/org/dashevo/examples/DisplayContracts.kt
examples/src/main/kotlin/org/dashevo/examples/GetStatus.kt
examples/src/main/kotlin/org/dashevo/examples/PreorderdNames.kt
examples/src/main/kotlin/org/dashevo/examples/PreorderedNames.kt
examples/src/main/kotlin/org/dashevo/examples/RegisteredNames.kt
examples/src/main/kotlin/org/dashevo/examples/SearchNames.kt
examples/src/main/kotlin/org/dashevo/examples/ShowContactRequests.kt
platform-core/build.gradle
platform-core/src/main/kotlin/org/dashevo/platform/ContractInfo.kt
platform-core/src/main/kotlin/org/dashevo/platform/Contracts.kt
platform-core/src/main/kotlin/org/dashevo/platform/Documents.kt
platform-core/src/main/kotlin/org/dashevo/platform/Identities.kt
platform-core/src/main/kotlin/org/dashevo/platform/Names.kt
platform-core/src/main/kotlin/org/dashevo/platform/Platform.kt

Related PR's:
dpp: https://github.com/dashevo/android-dpp/pull/6
dapi-client: https://github.com/dashevo/dapi-client-android/pull/6

Update to DPP 0.13

---

platform-core/src/main/kotlin/org/dashevo/platform/Platform.kt

This will update the contracts for Mobile and Evonet

Update Evonet / Mobile Contracts for 0.14

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/ContactRequests.kt
examples/src/main/kotlin/org/dashevo/examples/ShowContactRequests.kt

The createdAt field the time in milliseconds (Long).

DashPay Contract: support the createdAt time stamp

---

dashpay/build.gradle
examples/build.gradle
platform-core/build.gradle

Changes required by https://github.com/dashevo/dash-wallet/pull/417

Switching the whole DashPay to protobuf-javalite

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/Profiles.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/callback/UpdateProfileCallback.kt
examples/src/main/kotlin/org/dashevo/examples/CreateWallets.kt

Depends on: https://github.com/dashevo/android-dpp/pull/10

DashPay: Create/Replace Profiles

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
platform-core/src/main/kotlin/org/dashevo/platform/Identities.kt

Support restoring an identity from the first public key.
This PR depends on #23, which should be merged first.

Chain Sync Phase 3A - Restore Identity from 1st Public Key

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/ContactRequests.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/Profiles.kt
dashpay/src/test/kotlin/PlatformTests.kt
examples/src/main/kotlin/org/dashevo/examples/GetStatus.kt
platform-core/src/main/kotlin/org/dashevo/platform/Documents.kt
platform-core/src/main/kotlin/org/dashevo/platform/Identities.kt
platform-core/src/main/kotlin/org/dashevo/platform/Names.kt
platform-core/src/main/kotlin/org/dashevo/platform/Platform.kt

Modify the GetStatus example to query every node of the network as a means to test the timeout changes in PR https://github.com/dashevo/dapi-client-android/pull/13
None

GetStatus: Query every node of the network

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/Profile.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/Profiles.kt
examples/src/main/kotlin/org/dashevo/examples/CreateWallets.kt

Avatar Hash and Fingerprint

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/ContactRequest.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/ContactRequests.kt
examples/src/main/java/org/dashevo/examples/ForwardingServiceEvo.java
examples/src/main/kotlin/org/dashevo/examples/CreateContract.kt
examples/src/main/kotlin/org/dashevo/examples/CreateIdentity.kt
examples/src/main/kotlin/org/dashevo/examples/DefaultIdentity.kt
examples/src/main/kotlin/org/dashevo/examples/GetStatus.kt
examples/src/main/kotlin/org/dashevo/examples/PreorderedNames.kt
examples/src/main/kotlin/org/dashevo/examples/RegisteredNames.kt
examples/src/main/resources/org/dashevo/examples/dashpay-contract.json
platform-core/src/main/kotlin/org/dashevo/Client.kt
platform-core/src/main/kotlin/org/dashevo/platform/Identities.kt
platform-core/src/main/kotlin/org/dashevo/platform/Platform.kt
tools/build.gradle
tools/generate-report.bat
tools/generate-report.sh
tools/src/main/java/org/dashevo/tools/WalletTool.java

These are the DPP 0.17 related updates
https://github.com/dashevo/dashj/pull/103

DPP 0.17 upgrade

---

examples/src/main/kotlin/org/dashevo/examples/GetNetworkStatus.kt

dependency:  https://github.com/dashevo/dapi-client-android/pull/15

Add GetNetworkStatus example

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/Profiles.kt
examples/src/main/kotlin/org/dashevo/examples/GetNetworkStatus.kt
platform-core/src/main/kotlin/org/dashevo/platform/Documents.kt
platform-core/src/main/kotlin/org/dashevo/platform/Platform.kt

#37
https://github.com/dashevo/dapi-client-android/pull/16
https://github.com/dashevo/dapi-client-android/pull/15

Add retry support for getDocuments

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
platform-core/src/main/kotlin/org/dashevo/platform/Platform.kt

Platform.check did not handle all possible exceptions in the case of an unstable or unavailable network
When creating a profile with `Blockchain.registerProfile`, check for the existence of the profile to avoid a `DuplicateDocumentError`.
The exact conditions to replicate the errors fixed were not repeated.
None

NMA-844, 842: Fix Platform available crash and profile creation bug

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt

BlockchainIdentity: Update invite string

---

dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/ContactRequests.kt
dashpay/src/main/kotlin/org/dashevo/dashpay/Profiles.kt
platform-core/src/main/kotlin/org/dashevo/platform/Documents.kt
platform-core/src/main/kotlin/org/dashevo/platform/Names.kt
platform-core/src/test/kotlin/org/dashevo/platform/DocumentsTest.kt
platform-core/src/test/kotlin/org/dashevo/platform/NamesTest.kt
platform-core/src/test/kotlin/org/dashevo/platform/PlatformNetwork.kt
tools/src/main/kotlin/org/dashevo/tools/NetworkActivity.kt

This PR will allow more than 100 contacts to be supported.
Also refactors some get functions.

Support Contacts > 100

---

.github/workflows/tests.yml
README.md
build.gradle
dashpay/build.gradle
dashpay/src/main/kotlin/org/dashevo/dashpay/BlockchainIdentity.kt
dashpay/src/test/kotlin/org/dashevo/dashpay/PlatformNetwork.kt
examples/build.gradle
examples/src/main/java/org/dashevo/examples/ForwardingServiceEvo.java
examples/src/main/kotlin/org/dashevo/examples/DefaultIdentity.kt
examples/src/main/kotlin/org/dashevo/examples/GetNetworkStatus.kt
examples/src/main/kotlin/org/dashevo/examples/GetStatus.kt
examples/src/main/kotlin/org/dashevo/examples/SearchNames.kt
platform-core/build.gradle
platform-core/src/main/kotlin/org/dashevo/platform/Identities.kt
platform-core/src/main/kotlin/org/dashevo/platform/Platform.kt
platform-core/src/main/kotlin/org/dashevo/platform/PlatformStateRepository.kt
tools/build.gradle
tools/generate-report.bat
tools/generate-report.sh
tools/src/main/kotlin/org/dashevo/tools/NetworkActivity.kt

Depends on:
https://github.com/dashevo/android-dpp/pull/18
https://github.com/dashevo/dapi-client-android/pull/21

feat: Update to DPP 0.19

---

examples/src/main/kotlin/org/dashevo/examples/GetNetworkStatus.kt
platform-core/src/main/kotlin/org/dashevo/platform/Platform.kt

Ban nodes that haven't been upgraded to v0.19

Testnet v0.19 Updates (NMA-891)

---

platform-core/src/main/kotlin/org/dashevo/platform/Platform.kt

chore: Update Palinka contract ids

---

dashpay/src/test/kotlin/PlatformTests.kt
dashpay/src/test/kotlin/org/dashj/platform/dashpay/PlatformNetwork.kt
examples/src/main/java/org/dashj/platform/examples/ForwardingServiceEvo.java
examples/src/main/kotlin/org/dashj/platform/examples/CreateIdentity.kt
examples/src/main/kotlin/org/dashj/platform/examples/CreateWallets.kt
examples/src/main/kotlin/org/dashj/platform/examples/CreateWalletsWithBalance.kt
examples/src/main/kotlin/org/dashj/platform/examples/DefaultIdentity.kt
examples/src/main/kotlin/org/dashj/platform/examples/RegisterNames.kt
examples/src/main/kotlin/org/dashj/platform/examples/ShowContactRequests.kt
examples/src/main/kotlin/org/dashj/platform/examples/WatchContactRequest.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/Client.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Platform.kt
platform-core/src/test/kotlin/org/dashj/platform/sdk/ClientTest.kt
platform-core/src/test/kotlin/org/dashj/platform/sdk/platform/PlatformNetwork.kt
tools/generate-report.bat
tools/generate-report.sh
tools/src/main/java/org/dashj/platform/tools/WalletTool.java
tools/src/main/kotlin/org/dashj/platform/tools/NetworkEnum.kt

refactor: Remove obsolete networks

---

README.md
build.gradle
dashpay/build.gradle
dashpay/src/main/kotlin/org/dashj/platform/dashpay/BlockchainIdentity.kt
dashpay/src/test/kotlin/org/dashj/platform/dashpay/PlatformNetwork.kt
examples/src/main/kotlin/org/dashj/platform/examples/CreateWallets.kt
examples/src/main/kotlin/org/dashj/platform/examples/DefaultIdentity.kt
examples/src/main/kotlin/org/dashj/platform/examples/GetIdentity.kt
examples/src/main/kotlin/org/dashj/platform/examples/GetIdentityFromSeed.kt
examples/src/main/kotlin/org/dashj/platform/examples/UpdateProfile.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/AbstractDocument.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Contracts.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Platform.kt

Updates for 0.21
see also:
dpp: https://github.com/dashevo/android-dpp/pull/24

DPP 0.21 Updates

---

dashpay/src/main/kotlin/org/dashj/platform/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashj/platform/dashpay/Profiles.kt
tools/build.gradle
tools/generate-report.bat
tools/generate-report.sh
tools/src/main/java/org/dashj/platform/tools/WalletTool.java
tools/src/main/kotlin/org/dashj/platform/tools/DashPayWallet.kt
tools/src/main/kotlin/org/dashj/platform/tools/NetworkActivity.kt

This fixes and improves two tools:
* WalletTool
* NetworkActivity

NMA-1029: Improve connectivity of tools and other fixes/improvements

---

dashpay/src/test/kotlin/org/dashj/platform/dashpay/PlatformNetwork.kt
examples/src/main/kotlin/org/dashj/platform/examples/DefaultIdentity.kt
examples/src/main/kotlin/org/dashj/platform/examples/UpdateProfile.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Platform.kt
platform-core/src/test/kotlin/org/dashj/platform/sdk/platform/PlatformNetwork.kt

fix: update schnapps contract ids

---

build.gradle
dashpay/build.gradle
examples/build.gradle
examples/src/main/kotlin/org/dashj/platform/examples/CreateIdentity.kt
examples/src/main/kotlin/org/dashj/platform/examples/DefaultIdentity.kt
platform-core/build.gradle
platform-core/src/test/kotlin/org/dashj/platform/sdk/platform/IdentitiesTest.kt
tools/src/main/java/org/dashj/platform/tools/WalletTool.java

Feature: core 0.18 (NMA-1095)

---

dashpay/src/main/kotlin/org/dashj/platform/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashj/platform/dashpay/ContactRequests.kt

fix: allow obtaining identity from platform at a later time

---

README.md
build.gradle
dashpay/src/main/kotlin/org/dashj/platform/dashpay/BlockchainIdentity.kt
dashpay/src/test/kotlin/org/dashj/platform/dashpay/PlatformNetwork.kt
examples/build.gradle
examples/src/main/java/org/dashj/platform/examples/ForwardingServiceEvo.java
examples/src/main/kotlin/org/dashj/platform/examples/DefaultIdentity.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/Client.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Identities.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Platform.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/PlatformStateRepository.kt
tools/src/main/java/org/dashj/platform/tools/WalletTool.java

DPP 0.22 updates

---

dashpay/src/main/kotlin/org/dashj/platform/dashpay/Profiles.kt
examples/src/main/kotlin/org/dashj/platform/examples/DefaultIdentity.kt
examples/src/main/kotlin/org/dashj/platform/examples/GetNetworkStatus.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Platform.kt

Updating a few things for Platform and Testnet 0.22

Testnet 0.22

---

build.gradle
platform-core/src/test/kotlin/org/dashj/platform/sdk/platform/DocumentsTest.kt

Support Core 18

---

platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Names.kt

docs: update search documentation

---

README.md
build.gradle
dashpay/src/main/kotlin/org/dashj/platform/dashpay/BlockchainIdentity.kt
dashpay/src/main/kotlin/org/dashj/platform/dashpay/ContactRequests.kt
dashpay/src/test/kotlin/org/dashj/platform/dashpay/PlatformNetwork.kt
examples/src/main/java/org/dashj/platform/examples/ForwardingServiceEvo.java
examples/src/main/kotlin/org/dashj/platform/examples/CreateIdentity.kt
examples/src/main/kotlin/org/dashj/platform/examples/CreateWallets.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/Client.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Identities.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Platform.kt
platform-core/src/test/kotlin/org/dashj/platform/sdk/ClientTest.kt
platform-core/src/test/kotlin/org/dashj/platform/sdk/platform/PlatformNetwork.kt
tools/src/main/java/org/dashj/platform/tools/WalletTool.java

Support DPP 0.23
Depends on:
https://github.com/dashevo/android-dpp/pull/33
https://github.com/dashevo/dapi-client-android/pull/43
https://github.com/dashevo/dashj/pull/166

Support DPP 0.23

---

build.gradle
dashpay/src/main/kotlin/org/dashj/platform/contracts/wallet/TxMetadataDocument.kt
dashpay/src/main/kotlin/org/dashj/platform/contracts/wallet/TxMetadataItem.kt
dashpay/src/main/kotlin/org/dashj/platform/dashpay/BlockchainIdentity.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Platform.kt

This PR includes various fixes to support syncing of tx metadata
Depends on:
https://github.com/dashevo/android-dpp/pull/35

Fix: tx metadata

---

build.gradle
examples/src/main/kotlin/org/dashj/platform/examples/CreateTxMetadata.kt
examples/src/main/kotlin/org/dashj/platform/examples/DefaultIdentity.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/Client.kt
platform-core/src/main/kotlin/org/dashj/platform/sdk/platform/Platform.kt
platform-core/src/test/kotlin/org/dashj/platform/sdk/platform/IdentitiesTest.kt
platform-core/src/test/kotlin/org/dashj/platform/sdk/platform/PlatformNetwork.kt

feat: add ouzo support for app 0.23
